name: Auto Draft PR on First Commit

on:
  push:
    branches-ignore:
      - main

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Get commit count on branch
        run: |
          COMMITS=$(git rev-list --count HEAD)
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV

      - name: Create draft PR if first commit
        if: env.COMMITS == '1'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          gh pr create --base main --head "$BRANCH_NAME" --title "Draft PR: $BRANCH_NAME" --draft