name: Release PR File Check

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  check-required-files:
    runs-on: ubuntu-latest
    # Only run if the PR has the 'release' label
    if: contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for required files
        shell: bash
        run: |
          echo "Checking for required files in pull request with 'release' label..."
          
          errorCount=0
          
          # Check for README.md
          if [ -f "README.md" ]; then
            echo "✅ README.md found"
          else
            echo "❌ README.md is missing"
            errorCount=$((errorCount + 1))
          fi
          
          # Check for run.bat
          if [ -f "run.bat" ]; then
            echo "✅ run.bat found"
          else
            echo "❌ run.bat is missing"
            errorCount=$((errorCount + 1))
          fi
          
          # Check for releases folder
          if [ -d "releases" ]; then
            echo "✅ releases/ folder found"
            
            # Check if there are any .exe files in the releases folder
            releaseFiles=$(find releases/ -name "*.exe" -type f | wc -l)
            if [ $releaseFiles -gt 0 ]; then
              echo "✅ Found $releaseFiles .exe file(s) in releases/ folder"
              echo "Release executables:"
              find releases/ -name "*.exe" -type f | sed 's/^/  - /'
            else
              echo "❌ No .exe files found in releases/ folder"
              errorCount=$((errorCount + 1))
            fi
          else
            echo "❌ releases/ folder is missing"
            errorCount=$((errorCount + 1))
          fi
          
          # Summary
          echo ""
          echo "=== Summary ==="
          if [ $errorCount -eq 0 ]; then
            echo "✅ All required files are present!"
            exit 0
          else
            echo "❌ $errorCount required file(s) missing!"
            echo ""
            echo "Required files for release PR:"
            echo "  - README.md (in root directory)"
            echo "  - run.bat (in root directory)"
            echo "  - At least one .exe file in releases/ folder"
            exit 1
          fi
